name: bloc_counter
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed: ^2.5.2
  go_router: ^13.2.4
  freezed_annotation: ^2.4.1
  google_fonts: ^6.2.1

  cupertino_icons: ^1.0.6


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.0.0
  bloc: ^8.0.0
  bloc_test: ^9.1.7 


  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

